### ISSUE TITLE
Example Complement

### ISSUE THREAD

**Issue by claudiojulioferraz** [dmotz/trystero#12]
Hi! I tried following your example to create a voice chat, but it doesn't work. Peers are connected, but there is no audio. Should I add a track? How it works?

```
import {joinRoom} from 'trystero';

const config = {appId: 'test08658'};

const room = joinRoom(config, 'vox');

room.addStream(navigator.mediaDevices.getUserMedia({audio: true, video: false}));
```

**Comment by dmotz** [comment]
Your example is almost there: you're having peers send their own streams, but you're not handling another peer's stream when it arrives.

To do that you need to add something like this:

```javascript

// create an object to store audio elements for peers
const peerAudio = {}

room.onPeerStream((stream, peerId) => {
  const audio = new Audio()
  audio.srcObject = stream
  audio.autoplay = true
  peerAudio[peerId] = audio
})
```

Handling a video stream would be a similar process, but with video elements instead. They would also have to be added to the DOM for the user to see them.

**Comment by claudiojulioferraz** [comment]
Thanks!
