### ISSUE TITLE
non web dev version

### ISSUE THREAD

**Issue by TheBricktop** [dmotz/trystero#14]
Is there a possibility to use the same technique to for example a native app in android or other operating system? 
I know that node js could be encapsulated in an app or run alongside as a relay but Im more into tightly integrating it into one app code.

**Comment by dmotz** [comment]
You could certainly use the same techniques to establish p2p connections in native code. If you wanted to use Trystero you could maybe use it inside a webview that passes messages between it and the native layer. You could also try using it with React Native but you'll have to use the WebRTC module with it.
