### ISSUE TITLE
[feature request] support webtorrent

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [dmotz/trystero#15]
We are about to write modules for Trystero here https://github.com/worldpeaceenginelabs/True-P2P
(starting with a webtorrent module)

Did you have any plans to do so? Or maybe in the pipeline? Upcoming? Ready somewhere?

**Comment by dmotz** [comment]
The current torrent module is a WebTorrent implementation as that's the only way I'm aware of for a browser to connect directly to a torrent tracker.

**Comment by worldpeaceenginelabs** [comment]
Thx for your fast answer.

Oh maybe i am wrong in my understanding?
It looks like you implemented the bittorrent dht, which is different from the webtorrent dht (so i thought?)

So your app does connections via bittorrent-dht (like you write in the description), webtorrent-dht (which is the same? i just read, bittorrent-dht is part of it, but from the browser), IPFS and Firebase???

That would be awesome! Can you confirm or explain, please?

**Comment by worldpeaceenginelabs** [comment]
I know bittorent uses tcp udp, which is not supported by browsers.
So as i understand now, the right description in your readme would be webtorrent, right?
A term which can be used equivalent to each other with background information i guess.
But yours is webtorrent, not bittorrent, right?

**Comment by dmotz** [comment]
Yes, since more people are familiar with BitTorrent in general (versus WebTorrent), Trystero uses that term instead. In the end Trystero is only using a very small part of the spec for exchanging peer IPs over tracker servers (in this case via WebSockets).
