### ISSUE TITLE
P2PT as a fallback for Trystero? Or does Trystero already do exact the same?

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [dmotz/trystero#16]
Does Trystero basically what P2PT does as well? It creates a torrent based on a 'topic' and peers interested in that topic swarm around that torrent and connect to each other?

If not, whats the difference? How exactly does Trystero do it?

**I like to use P2PT as a fallback for Trystero, but maybe Trystero does already, was P2PT does?**

Every client is also a tracker itself, so its able to fetch connection adresses (DHT)

1. direct (webrtc) and indirect (torrents, IPFS) (webrtc prioritized, Trystero reconnects through torrents and ipfs as a fallback)
2. indirect/fallback (torrent/magnetlink) ([P2PT](https://github.com/subins2000/p2pt)) reconnect, than back to 1. (direct)

**Comment by dmotz** [comment]
What you describe is basically what it does. The torrent strategy in Trystero simply uses a torrent tracker as a pub/sub server for exchanging peer connection data. All the strategies use their respective medium to exchange initial peer connection data, but after that peers always exchange data directly via WebRTC.

**Comment by worldpeaceenginelabs** [comment]
thx.

So p2pt is unneccesary, because Trystero is already doing this, right?

My idea was:

use of a torrent as a beacon. So your app only has the name /signature of a torrent saved, which nobody knows about, except your app (like a secret). Everybody who is interested in this torrent (only people with your app, nobody else knows), is potentially one of your users, so you connect to them. For security, you could exchange this torrent from time to time, which is like changing the secret address or password from time to time.

Trystero already does this, right? (minus the secret signature, but i can add that if not)
Hope i am not bothering you too much, but its my last question.

Kind regards

**Comment by dmotz** [comment]
Yes that's correct, Trystero does this behavior.

```javascript
import {joinRoom} from 'trystero'

const room = joinRoom({appId: 'your_app_id'}, 'some_secret_namespace')
```

In the above code, Trystero is broadcasting an info hash to torrent trackers that's a hash of the `appId` and the namespace argument (in your case a secret string). Any other peers who know both strings should be able to connect.

You can also add a `password` field to that first config object and Trystero will encrypt the session packets the torrent trackers exchange. See [this](https://github.com/dmotz/trystero#encryption) in the readme for details. This password string must match across all peers to connect.

**Comment by worldpeaceenginelabs** [comment]
Wow. Your repository is far underestimated 🙏🏼🙏🏼🙏🏼
You should update your readme, to make people aware, of what its actually able to do.

Thank you so much for your work and your answers.
Have a great day.

PS: i would appreciate, we both working together on this.
