### ISSUE TITLE
would the bugout module be useful for trystero?

### ISSUE THREAD

**Issue by resession** [dmotz/trystero#17]
https://github.com/chr15m/bugout

it uses webtorrent to connect users through webrtc. you can run a backend with the browser tab.

**Comment by dmotz** [comment]
I think Bugout is doing something close to the torrent strategy in Trystero — using public trackers to exchange peer info and then adding an event abstraction on top of the peer connections. Let me know if I'm misinterpreting though.

**Comment by resession** [comment]
Now that i read more bugouts source code. You seem to have it correct. They are using public trackers to exchange data and yake care of the signaling. Though im wondering which modupe is more efficient. But essentially the torrent strategy of trystero is using the same mechanism so i'll close this out.
