### ISSUE TITLE
typescript types

### ISSUE THREAD

**Issue by JohnDeved** [dmotz/trystero#18]
typescript types for the library would be neat.

**Comment by jeremyckahn** [comment]
I've got Trystero types defined for my own TypeScript-based project: https://github.com/jeremyckahn/chitchatter/blob/f0a440491094da1917e1e04d7cc0782576358dd2/src/react-app-env.d.ts#L4-L102

I will work to get this into a PR soon!

**Comment by dmotz** [comment]
Types are now available in 0.11.3 on npm.
