### ISSUE TITLE
Custom IPFS Gateway

### ISSUE THREAD

**Issue by vexxvakan** [dmotz/trystero#25]
We are currently looking into using Trystero for our decentralised gaming client. 

Is it possible to use our custom IPFS gateway instead of a public one to guarantee uptime?

**Comment by dmotz** [comment]
Yes, in the config object you pass to `joinRoom()` (using the IPFS strategy) you can specify a `swarmAddresses` property which expects an array of addresses ([for reference](https://github.com/dmotz/trystero/blob/main/src/ipfs.js#L27)). 

Check out [@libp2p/webrtc-star-signalling-server
](https://github.com/libp2p/js-libp2p-webrtc-star/tree/master/packages/webrtc-star-signalling-server) for more details on running a signaling server.

**Comment by dmotz** [comment]
Feel free to reopen if you have any questions.
