### ISSUE TITLE
Reconnecting doesn't work properly with Firebase 

### ISSUE THREAD

**Issue by tylerbonnell** [dmotz/trystero#27]
Repro steps:
- User 1 creates a room with a hardcoded app ID and room ID
- User 2 joins the room
- User 2 calls `room.leave()`
- User 2 attempts to join the room again, without refreshing. Same app ID, room ID, and peer ID. 
- **The `onPeerJoin` function does not execute for User 1.**
- If I switch the backend to bittorrent, it works fine. It also works fine on a refresh when a new peer ID is generated.

I'm guessing this has something to do with entries in `connectedPeers` or `peerMap` not being properly evicted on a disconnect, but I haven't had a chance to familiarize myself with the Firebase API or everything `trystero/firebase.js` is doing.

**Comment by dmotz** [comment]
Thanks for reporting this! It should be fixed now in the latest version on npm (0.11.6).
