### ISSUE TITLE
I made a mobile 'PWA'  with your library.

### ISSUE THREAD

**Issue by rocket-pig** [dmotz/trystero#34]
Not an issue! Just wanted to share and thank you again. 

https://github.com/rocket-pig/rocket-pig.github.io

All thanks to your mighty library.  Its coding amateur-hour compared to you but I had fun making it.  Thanks again for sharing your code!

**Comment by jeremyckahn** [comment]
Nice work @rocket-pig! I am also a huge fan of Trystero. Thanks to @dmotz for all the great work with this amazing library! I've used it for two projects of mine as well:

- https://chitchatter.im/ (https://github.com/jeremyckahn/chitchatter)
- https://www.farmhand.life/ (https://github.com/jeremyckahn/farmhand)

It looks like we're thinking along the same lines with Hullo and Chitchatter. 🙂

**Comment by rocket-pig** [comment]
Very cool! Youre quite the coder. I almost stopped before I started when I found Chitchatter thinking 'someone's already done this' but I'm glad I didn't, I learn best by doing. I spent some time in Farmhand-land too and it inspired me to read about game design...you did /are doing an amazing job on both.  

You could add the #trystero tag to your repos...I did to mine..  Hope that's not too forward of me :D

**Comment by jeremyckahn** [comment]
@rocket-pig there's always space for new projects! I'm glad you kept on and made Hullo. It's a great app! I really like the addition of the devtools. It's a nice touch!

Thanks for your kind words about Farmhand and Chitchatter! I added the `#trystero` tag as you suggested to both. Good idea! 🙂

**Comment by rocket-pig** [comment]
Whoops I had not intended to leave devtools on there.    It's silly that such functionality is difficult to come by on mobile.  Great for testing. I wrote the entire app on the phone itself so Eruda is invaluable.  Not sure it's use to "end user" though. Thx again for kind n encouraging words.

**Comment by dmotz** [comment]
Nice work @rocket-pig! My goal with Trystero was to lower the friction in creating p2p web apps, so thrilled to see new ones come on the scene.
