### ISSUE TITLE
WebRTC: ICE failed

### ISSUE THREAD

**Issue by ghost** [dmotz/trystero#36]
Hi,
Thanks a lot for making this abstract handy library !!!

As for the results, I already had it running without problems, then all of a sudden I'm having:

> WebRTC: ICE failed, add a TURN server and see about:webrtc for more details

So when I check I have the followings:

![image](https://user-images.githubusercontent.com/10267332/221249139-9fead4ba-3fe5-44ef-a1b8-0c171b43bdf1.png)

I don't know anything about bittorrent network, any help is so much appreciated !!

Edit:
All I'm doing is the basic example of one server `joinRoom` and same for clients. I'm using client sessions (chrome, firefox)

Thanks a lot

**Comment by dmotz** [comment]
Does this occur in other browsers?

If your network is blocking you could try setting up TURN using something like [Open Relay](https://www.metered.ca/tools/openrelay/#-how-to-use)

```javascript
joinRoom({
  appId: 'yourAppId',
  rtcConfig: {
    iceServers: [
      {
        urls: 'stun:relay.metered.ca:80'
      },
      {
        urls: 'turn:relay.metered.ca:80',
        username: 'your-turn-server-username',
        credential: 'your-turn-server-password'
      },
      {
        urls: 'turn:relay.metered.ca:443',
        username: 'your-turn-server-username',
        credential: 'your-turn-server-password'
      },
      {
        urls: 'turn:relay.metered.ca:443?transport=tcp',
        username: 'your-turn-server-username',
        credential: 'your-turn-server-password'
      }
    ]
  }
})

```
