### ISSUE TITLE
What is needed to self-host with custom BT trackers?

### ISSUE THREAD

**Issue by Tails** [dmotz/trystero#46]
Trystero looks amazing. I'm evaluating it as a solution for p2p "rooms" that span different blockchain nodes in a new blockchain network.

Suppose every node in my blockchain network would be hosting a torrent tracker, can Trystero be configured to use these as opposed to the hardcoded public ones?

**Comment by jeremyckahn** [comment]
Trystero accepts a `trackerUrls` configuration option: https://github.com/dmotz/trystero#joinroomconfig-namespace

I use this to connect to a local tracker during development. I imagine it would work for your use case as well!
