### ISSUE TITLE
Does Trystero only support wss:// trackers?

### ISSUE THREAD

**Issue by Tails** [dmotz/trystero#47]
I'm trying to hook up Trystero to a [Torrust tracker](https://github.com/torrust/torrust-tracker) but it only supports HTTP and UDP announce endpoints. It seems Trystero only supports websocket connections, is that correct?

**Comment by Tails** [comment]
The documentation mentions it inline, sorry. "Must support Websocket connections"

**Comment by dmotz** [comment]
I don't know if Torrust or any other tracker servers support HTTP/3 but the recent [WebTransport API](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport_API) allows browsers to do lower level connections that aren't WebSockets. I'd be happy to see Trystero support this if it's feasible and allows interop with other types of tracker servers.
