### ISSUE TITLE
Binary/Blob truncation on receiver

### ISSUE THREAD

**Issue by lmangani** [dmotz/trystero#5]
The "binary" pipeline example using `makeAction` appears to be only presenting a chunk of actual data to the `get` client:
```
const [sendPic, getPic] = room.makeAction('pic')

// blobs are automatically handled, as are any form of TypedArray
canvas.toBlob(blob => sendPic(blob))

// binary data is received as raw ArrayBuffers so your handling code should
// interpret it in a way that makes sense
getPic((data, id) => (imgs[id].src = URL.createObjectURL(new Blob([data]))))
```

This seems easy to reproduce by sending anything (image or else) larger than a few KBs over to see it truncated using the bittorrent strategy room. Interestingly enough, the overall blob size on the receiver seems correct, but filled with `0`/`null` values past the first valid chunk.

Did anyone succeed in transmitting full Blobs with the above (and/or any variation)?

Thanks in advance!

**Comment by dmotz** [comment]
Thanks for reporting this. I'd made a change at one point that broke handling large files. I just pushed 0.7.11 to npm which should fix the issue.
