### ISSUE TITLE
Can all peers see each others IP addresses?

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [dmotz/trystero#54]
Just wondering how secure/anonymous trystero is.

If I create a room and a number of users join, can they all see the IP addresses of the other people? And if so how easy is that to access?

**Comment by jeremyckahn** [comment]
AFAIK peer IP addresses are exposed to others via SDP strings. These strings are obtained from the pairing mechanism (WebTorrent/IPFS/Firebase) and used to locate and connect peers. I don't know that a WebRTC connection can be established without some sort of SDP string exchange.

**Comment by dmotz** [comment]
Yes given that they're p2p connections a savvier user could use some network monitoring tools to view IP addresses but it's more complicated than simply opening up the browser dev inspector.
