### ISSUE TITLE
Callbacks and leave() seem unreliable?

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [dmotz/trystero#55]
Callbacks like `onPeerLeave` and `onPeerJoin` dont seem to be firing reliably? Especially `onPeerLeave`. Is this a known bug or issue?

I also notice that sometimes when trying to move a peer from one room to another, by calling `room.leave()` on the current room and then `joinRoom()` for the new one, that sometimes the user get stuck in both and continues to receive messages/data from both? To the point that even after calling leave() on a room, if other peers do a `room.getPeers()` call, it will continue to show the peer that should have been removed?

**Comment by dmotz** [comment]
Which strategy were you seeing this with (e.g. torrent)? Could you post some sample code that reproduces it? Thanks.

**Comment by dmotz** [comment]
Leave events should be much faster/more reliable in the latest release.
