### ISSUE TITLE
[Feature request] Use ipfs-mini 

### ISSUE THREAD

**Issue by sc0ttj** [dmotz/trystero#6]
It would be nice to use https://github.com/SilentCicero/ipfs-mini as a backend, if possible.

I don't know if this would be possible, as it's not a direct replacement to ipfs-core.

**Comment by dmotz** [comment]
Would love to slim down the huge size of the IPFS strategy, but Trystero relies on the pubsub feature of IPFS and ipfs-mini doesn't support it. Feel free to comment/reopen if you're aware of another small library that can handle pubsub.

**Comment by Ruulul** [comment]
> Would love to slim down the huge size of the IPFS strategy, but Trystero relies on the pubsub feature of IPFS and ipfs-mini doesn't support it. Feel free to comment/reopen if you're aware of another small library that can handle pubsub.

what about using libp2p directly?
