### ISSUE TITLE
Add nostr support?

### ISSUE THREAD

**Issue by freehuntx** [dmotz/trystero#62]
Nostr can be used to signaling for free. See: https://github.com/nbd-wtf/nostr-tools

**Comment by dmotz** [comment]
Yes, I have a Nostr implementation in progress at the moment! I'll update this issue when it lands.

**Comment by freehuntx** [comment]
Also MQTT looks interesting :) There are alot of MQTT Broker out there that can be used for free.

**Comment by dmotz** [comment]
@freehuntx could you post links regarding open MQTT brokers?

**Comment by freehuntx** [comment]
https://www.hivemq.com/mqtt/public-mqtt-broker/
wss://broker.hivemq.com:8884

https://www.emqx.com/en/mqtt/public-mqtt5-broker
wss://broker.emqx.io:8084

https://test.mosquitto.org/
wss://test.mosquitto.org:8080

Client:
https://github.com/mqttjs/MQTT.js

**Comment by dmotz** [comment]
@freehuntx I just published 0.17.0 which includes an MQTT strategy. Thanks for suggesting it!

**Comment by freehuntx** [comment]
Nice! I will check it out 👍

**Comment by dmotz** [comment]
@freehuntx 0.18.0 features a new Nostr strategy

**Comment by freehuntx** [comment]
Awesome :D Nice work man!
