### ISSUE TITLE
[Feature request] support Supabase

### ISSUE THREAD

**Issue by sc0ttj** [dmotz/trystero#7]
Use https://github.com/supabase/supabase-js as well as / instead of Firebase.

**Comment by dmotz** [comment]
I've looked at Supabase and considered it for Trystero but its API lacks a disconnect handler which is important for cleaning up a peer's session info when they leave. Without it the database will fill with junk data about peers who are no longer around. That said, there might be a different strategy for cleanup and I'll give it some thought.

**Comment by dmotz** [comment]
The latest release now supports Supabase as a peering strategy.
