### ISSUE TITLE
RTCPeerConnection is not defined

### ISSUE THREAD

**Issue by rockey2020** [dmotz/trystero#70]
When I use in node.js 21

```
const config = { appId: "wo_shi_ce_shi_10086" };
  const room = joinRoom(config, "yoyodyne");

  room.onPeerJoin((peerId) => console.log(`${peerId} joined`));

```

**Comment by jeremyckahn** [comment]
This is happening because Trystero uses WebRTC, which is not available in NodeJS (see #24).

**Comment by rockey2020** [comment]
https://github.com/murat-dogan/node-datachannel

At present, node-datachannel is stable and can be used in production environments. I wonder if there are any plans to replace it with this one?

**Comment by jeremyckahn** [comment]
> https://github.com/murat-dogan/node-datachannel
> 
> At present, node-datachannel is stable and can be used in production environments. I wonder if there are any plans to replace it with this one?

That seems like a great idea. I'll play around with using it as a polyfill when I have some time!

**Comment by dmotz** [comment]
Let's move this discussion over to #24.

**Comment by dmotz** [comment]
Node support is now working in 0.21.2, see https://github.com/dmotz/trystero?tab=readme-ov-file#running-server-side-node-deno-bun for details.
