### ISSUE TITLE
accessing your own peerId

### ISSUE THREAD

**Issue by hchiam** [dmotz/trystero#72]
Hi! I'm new to trystero - 
From [the current README](https://github.com/dmotz/trystero/blob/39539570abebf5e6ef42a8463ac90764b02981cf/README.md), it didn't seem immediately obvious that for the js of a user to access their own peer ID `selfId`, you need to [do an import like](https://github.com/search?q=repo%3Admotz%2Ftrystero%20selfId&type=code) `import {selfId} from './nostr.js'` 

I get that it's technically at the same level of indentation in the README as the other things listed under API (like `joinRoom`), but any thoughts on adding a code snippet here?

<img width="656" alt="selfId_mentioned_inREADME" src="https://github.com/dmotz/trystero/assets/18131787/413ebc63-a846-4881-93c9-80546b8e544b">

Maybe we could add something like this?

```js
import {selfId} from 'trystero'
```

**Comment by coderofsalvation** [comment]
I also remember struggling with this, eventually I discovered I could access selfId as a global var (via variable hoisting?) : https://codeberg.org/coderofsalvation/xrfragment/src/branch/main/src/3rd/js/plugin/p2p/trystero.js#L54

however this example uses trystero-torrent.min.js, not the module version.

**Comment by dmotz** [comment]
Thanks for the suggestion, I added a section early in the readme mentioning how to do this.
