### ISSUE TITLE
Mentioned you in repo (again)

### ISSUE THREAD

**Issue by freehuntx** [dmotz/trystero#73]
Just letting you know, again your project really helped me to realize a cool thing.  
And i wanna thank you <3  
Mentioned in: https://github.com/freehuntx/bomberpengu?tab=readme-ov-file#trystero  

Trystero basically helps me to add multiplayer support to old flash games that once had multiplayer (using TCP).

**Comment by jeremyckahn** [comment]
Cool game @freehuntx! I've added it to https://github.com/jeremyckahn/awesome-trystero.

**Comment by dmotz** [comment]
I never could've imagined this project would find its way into a classic Flash game... 😄 This really fits Trystero's ethos of unexpected uses of tech. Thanks for sharing @freehuntx

**Comment by muniamunia** [comment]
I would love to play w/ you. This game was 1/3 of my childhood :D
