### ISSUE TITLE
Error: undefined 'digest' . (when accessing by ip address)

### ISSUE THREAD

**Issue by chopin** [dmotz/trystero#80]
Hi again,

I integrated Trystero for the first time.  I saw that  joinRoom() and room.onPeerJoin() worked fine when accessing by localhost.

But Trystero fail when I access by ip address  not localhost. Following is the error message:
```
trystero-torrent.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
    at C (trystero-torrent.min.js:1:516)
    at rr.init (trystero-torrent.min.js:1:47935)
```

I found the corresponding line at debugger around at line 23 in trystero-torrent.min.js:
```
const t = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-1", p(e)))).map((e=>e.toString(36))).join("");
```

I really appreciate your help. Thanks in advance.

**Comment by jeremyckahn** [comment]
Trystero uses the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API), which requires a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). What that means is that it will only work under `localhost` or `https` URLs. If you're on an IP URL, it's probably `http` and not `https`. So, you'll need to update your project to be served from a `https` URL.

**Comment by chopin** [comment]
Thanks for your response. I found a related issue posted before. It explains how to get SSL certificate in local device:
https://github.com/dmotz/trystero/issues/20#issue-1326257159
